# Generated by Django 2.2.6 on 2019-12-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0013_auto_20191223_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='friend',
        ),
        migrations.AddField(
            model_name='book',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='books', to='p_library.Friend'),
        ),
    ]
