# Generated by Django 2.2.6 on 2020-01-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0015_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='picture/%Y/%m/%d'),
        ),
    ]
