# Generated by Django 2.2.6 on 2020-01-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0017_auto_20200102_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
